FROM mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm

RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash \
  && sudo apt-get install git-lfs